### ISSUE TITLE
Upon opening/closing the preferences window before creating the first notebook, segfault happen.

### ISSUE THREAD

**Issue by matzipan** [Philip-Scott/Notes-up#105]
Stacktrace:
```
Thread 1 "notes-up" received signal SIGSEGV, Segmentation fault.
0x000000000042ab79 in enotes_viewer_load_css ()
(gdb) bt
#0  0x000000000042ab79 in enotes_viewer_load_css ()
#1  0x000000000041d9fe in ?? ()
#2  0x000000000041d4e9 in ?? ()
#3  0x00007ffff5c9ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x00007ffff5cb1fc1 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff5cbad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff5cbb08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff5ca01d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007ffff5cba9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007ffff5cbb08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007ffff6a606ad in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007ffff6a60715 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007ffff5c9ffa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff5cb1afc in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007ffff5cbad5c in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007ffff5cbb08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007ffff6a5e7a0 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007fffed5e9e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#18 0x00007fffed5e98ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#19 0x00007ffff5ca0cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007ffff5ca01d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007ffff5cba9a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007ffff5cbb08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007ffff6b0c891 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#24 0x00007ffff5ca2dbe in g_cclosure_marshal_VOID__BOXEDv () from /usr/lib/x86_64-linux-gnu/libgobject-2.
```

Steps to reproduce:
1. Fresh install (or delete the .db file, and set org.notes.last-notebook and org.notes.last-page to 0)
2. Open preferences
3. Close preferences
4. Crash happens

**Comment by Philip-Scott** [comment]
Had the code that creates a new notebook and page commented out. Good catch! thanks :)
